# Generated by Django 5.0 on 2023-12-22 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='차 이름', max_length=100)),
                ('brand', models.CharField(help_text='차 브랜드', max_length=100)),
                ('vin', models.CharField(help_text='식별변호', max_length=10, unique=True)),
                ('price', models.IntegerField(help_text='가격')),
                ('is_sold', models.BooleanField(default=False)),
                ('features', models.ManyToManyField(related_name='cars', to='cars.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versions', models.IntegerField()),
                ('price', models.IntegerField(help_text='버전별 가격')),
                ('added_features', models.ManyToManyField(related_name='added_to_versions', to='cars.feature')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.car')),
                ('removed_features', models.ManyToManyField(related_name='removed_from_versions', to='cars.feature')),
            ],
        ),
        migrations.CreateModel(
            name='UsedCarSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('sale_price', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_sales', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_purchases', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsedVersions', to='cars.version')),
            ],
        ),
        migrations.CreateModel(
            name='CarSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('sale_price', models.IntegerField(help_text='구매 가격')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleVersions', to='cars.version')),
            ],
        ),
    ]
